### ISSUE TITLE
Filter Places: more prominent/larger?

### ISSUE THREAD

**Issue by sawernke** [LOGARANDES/logardata#7]
-Filter Places--a really great function--is a bit buried for the unititiated. Could it be made larger?
-The + sign next to the Audiencia, etc: when the cursor hovers over it, it changes to a text editing style cursor icon. Could that behavior be changed so the cursor remains an arrow?

**Comment by wsalesky** [comment]
@sawernke Can you clarify, do you mean on the home page map, or on the search results page?

**Comment by wsalesky** [comment]
Sure, I do something similar here: 
https://architecturasinica.org/geolocation.html

I can change the filter places to be open by default, but collapsable. Or just make the box more prominent. Let me know which you would prefer.

**Comment by sawernke** [comment]
Yes, that looks great!

**Comment by wsalesky** [comment]
Okay, I will rework that page.

**Comment by wsalesky** [comment]
Done. See: http://wwwb.library.vanderbilt.edu/exist/apps/logar/index.html

And: https://github.com/LOGARANDES/gazetteer-demo/commit/f606e3df235a6704d47b3bb9c611e42c54ae0a12
